### ISSUE TITLE
Unexisting dependencies

### ISSUE THREAD

**Issue by nico202** [JuliaRegistries/Uncurated#12]
Hi, I might be wrong but there are uuids used in dependencies that do not have a corresponding package, is this expected? I found those that are actually referred (if my script is right) by the highest package version. Like N/NetworkLearning/Versions.toml containing "0.1.0", N/NetworkLearning/Deps.toml containing Future "9fa8497b-333b-5362-9e8d-4d0656e87820", but this package does not exists:

- 2a0f44e3-6c83-55bd-87e4-b1978d98bd5f
- b77e0a4c-d291-57a0-90e8-8db25a27a240
- 8bf52ea8-c179-5cab-976a-9e18b702a9bc
- a63ad114-7e13-5084-954f-fe012c677804
- 37e2e46d-f89d-539d-b4ee-838fcccc9c8e
- 8bb1440f-4735-579b-a4ab-409b98df4dab
- 2f01184e-e22b-5df5-ae63-d93ebab69eaf
- 7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee
- 8dfed614-e22c-5e08-85e1-65c5234f0b40
- de0858da-6303-5e67-8744-51eddeeeb8d7
- 44cfe95a-1eb2-52ea-b672-e2afdf69b78f
- 8ba89e20-285c-5b6f-9357-94700520ee1b
- 9abbd945-dff8-562f-b5e8-e1ebf5ef1b79
- 1a1011a3-84de-559e-8e89-a11a2f7dc383
- 9a3f8284-a2c9-5f02-9a11-845980a1fd5c
- 8f399da3-3557-5675-b5ff-fb832c97cbdb
- 4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5
- de555fa4-b82f-55e7-8b71-53f60bbc027d
- 6462fe0b-24de-5631-8697-dd941f90decc
- 9fa8497b-333b-5362-9e8d-4d0656e87820

**Comment by KristofferC** [comment]
These are likely the standard libraries which are not registered in the registry.

**Comment by nico202** [comment]
Oh, fine, indeed they seems to be, eg: https://github.com/JuliaLang/julia/blob/2017524f22c88949fccaf5a7796fc7f2f068a43e/stdlib/Base64/Project.toml

Thanks :)
